version: "3.8"

services:
  model_predict_api:
    build:
      context: ../..
      dockerfile: service/model_api_serving/Dockerfile
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "7000:7000"
      - "8001:8001"
    environment:
      - JAEGER_URI=${JAEGER_OTLP_URI}
      - METRIC_EXPOSED_URI=${METRICS_URI}
    extra_hosts:
      - "host.docker.internal:host-gateway"
