channels:
- conda-forge
dependencies:
- python=3.9.21
- pip<=25.0
- pip:
  - mlflow<3,>=2.2
  - catboost==1.2.7
  - ipython==8.18.1
  - numpy==1.26.4
  - pandas==2.2.3
  - scipy==1.13.1
name: mlflow-env
